window.Modernizr=function(g,f,q){function e(b,c){var a=b.charAt(0).toUpperCase()+b.substr(1),a=(b+" "+t.join(a+" ")+a).split(" ");return z(a,c)}function z(b,c){for(var a in b)if(x[b[a]]!==q)return c=="pfx"?b[a]:!0;return!1}var j={},r=f.documentElement;f.head||f.getElementsByTagName("head");var i=f.createElement("modernizr"),x=i.style,u=" -webkit- -moz- -o- -ms- -khtml- ".split(" "),t="Webkit Moz O ms Khtml".split(" "),i={},h=[],s=function(b,c,a,d){var n,D,e=f.createElement("div");if(parseInt(a,10))for(;a--;)D=
f.createElement("div"),D.id=d?d[a]:"modernizr"+(a+1),e.appendChild(D);n=["&shy;<style>",b,"</style>"].join("");e.id="modernizr";e.innerHTML+=n;r.appendChild(e);b=c(e,b);e.parentNode.removeChild(e);return!!b},A=function(){var b={select:"input",change:"input",submit:"form",reset:"form",error:"img",load:"img",abort:"img"};return function(c,a){a=a||f.createElement(b[c]||"div");c="on"+c;var d=c in a;d||(a.setAttribute||(a=f.createElement("div")),a.setAttribute&&a.removeAttribute&&(a.setAttribute(c,""),
d=typeof a[c]==="function",typeof a[c]===q||(a[c]=q),a.removeAttribute(c)));return d}}(),l,v={}.hasOwnProperty,y;typeof v!==q&&typeof v.call!==q?y=function(b,c){return v.call(b,c)}:y=function(b,c){return c in b&&typeof b.constructor.prototype[c]===q};(function(b,c){var a=b.join(""),d=c.length;s(a,function(a){for(var a=a.childNodes,b={};d--;)b[a[d].id]=a[d];j.csstransforms3d=b.csstransforms3d.offsetLeft===9},d,c)})([,["@media (",u.join("transform-3d),("),"modernizr){#csstransforms3d{left:9px;position:absolute}}"].join("")],
[,"csstransforms3d"]);i.hashchange=function(){return A("hashchange",g)&&(f.documentMode===q||f.documentMode>7)};i.history=function(){return!!g.history&&!!history.pushState};i.borderradius=function(){return e("borderRadius")};i.boxshadow=function(){return e("boxShadow")};i.cssgradients=function(){var b=("background-image:"+u.join("gradient(linear,left top,right bottom,from(#9f9),to(white));background-image:")+u.join("linear-gradient(left top,#9f9, white);background-image:")).slice(0,-17);x.cssText=
b;return!!~(""+x.backgroundImage).indexOf("gradient")};i.csstransforms=function(){return!!z(["transformProperty","WebkitTransform","MozTransform","OTransform","msTransform"])};i.csstransforms3d=function(){var b=!!z(["perspectiveProperty","WebkitPerspective","MozPerspective","OPerspective","msPerspective"]);b&&"webkitPerspective"in r.style&&(b=j.csstransforms3d);return b};i.csstransitions=function(){return e("transitionProperty")};for(var w in i)y(i,w)&&(l=w.toLowerCase(),j[l]=i[w](),h.push((j[l]?
"":"no-")+l));x.cssText="";i=null;g.attachEvent&&function(){var b=f.createElement("div");b.innerHTML="<elem></elem>";return b.childNodes.length!==1}()&&function(b,c){function a(a){for(var k=-1;++k<f;)a.createElement(e[k])}b.iepp=b.iepp||{};var d=b.iepp,n=d.html5elements||"abbr|article|aside|audio|canvas|datalist|details|figcaption|figure|footer|header|hgroup|mark|meter|nav|output|progress|section|summary|time|video",e=n.split("|"),f=e.length,i=RegExp("(^|\\s)("+n+")","gi"),g=RegExp("<(/*)("+n+")",
"gi"),j=/^\s*[\{\}]\s*$/,h=RegExp("(^|[^\\n]*?\\s)("+n+")([^\\n]*)({[\\n\\w\\W]*?})","gi"),l=c.createDocumentFragment(),o=c.documentElement,n=o.firstChild,k=c.createElement("body"),p=c.createElement("style"),L=/print|all/,B;d.getCSS=function(a,k){if(a+""===q)return"";for(var b=-1,m=a.length,p,n=[];++b<m;)p=a[b],p.disabled||(k=p.media||k,L.test(k)&&n.push(d.getCSS(p.imports,k),p.cssText),k="all");return n.join("")};d.parseCSS=function(a){for(var k=[],d;(d=h.exec(a))!=null;)k.push(((j.exec(d[1])?"\n":
d[1])+d[2]+d[3]).replace(i,"$1.iepp_$2")+d[4]);return k.join("\n")};d.writeHTML=function(){var a=-1;for(B=B||c.body;++a<f;)for(var d=c.getElementsByTagName(e[a]),b=d.length,p=-1;++p<b;)d[p].className.indexOf("iepp_")<0&&(d[p].className+=" iepp_"+e[a]);l.appendChild(B);o.appendChild(k);k.className=B.className;k.id=B.id;k.innerHTML=B.innerHTML.replace(g,"<$1font")};d._beforePrint=function(){p.styleSheet.cssText=d.parseCSS(d.getCSS(c.styleSheets,"all"));d.writeHTML()};d.restoreHTML=function(){k.innerHTML=
"";o.removeChild(k);o.appendChild(B)};d._afterPrint=function(){d.restoreHTML();p.styleSheet.cssText=""};a(c);a(l);d.disablePP||(n.insertBefore(p,n.firstChild),p.media="print",p.className="iepp-printshim",b.attachEvent("onbeforeprint",d._beforePrint),b.attachEvent("onafterprint",d._afterPrint))}(g,f);j._version="2.0.6";j._prefixes=u;j._domPrefixes=t;j.mq=function(b){if(g.matchMedia)return matchMedia(b).matches;var c;s("@media "+b+" { #modernizr { position: absolute; } }",function(a){c=(g.getComputedStyle?
getComputedStyle(a,null):a.currentStyle).position=="absolute"});return c};j.hasEvent=A;j.testProp=function(b){return z([b])};j.testAllProps=e;j.testStyles=s;r.className=r.className.replace(/\bno-js\b/,"")+(" js "+h.join(" "));return j}(this,this.document);
(function(g,f){function q(){w(!0)}g.respond={};respond.update=function(){};respond.mediaQueriesSupported=f;if(!f){var e=g.document,z=e.documentElement,j=[],r=[],i=[],x={},u=e.getElementsByTagName("head")[0]||z,t=u.getElementsByTagName("link"),h=[],s=function(){for(var a=t.length,d=0,b,c,e,f;d<a;d++)b=t[d],c=b.href,e=b.media,f=b.rel&&b.rel.toLowerCase()==="stylesheet",!!c&&f&&!x[c]&&(!/^([a-zA-Z]+?:(\/\/)?(www\.)?)/.test(c)||c.replace(RegExp.$1,"").split("/")[0]===g.location.host?h.push({href:c,media:e}):
x[c]=!0);A()},A=function(){if(h.length){var a=h.shift();b(a.href,function(d){l(d,a.href,a.media);x[a.href]=!0;A()})}},l=function(a,d,b){var c=a.match(/@media[^\{]+\{([^\{\}]+\{[^\}\{]+\})+/gi),e=c&&c.length||0,d=d.substring(0,d.lastIndexOf("/")),f=function(a){return a.replace(/(url\()['"]?([^\/\)'"][^:\)'"]+)['"]?(\))/g,"$1"+d+"$2$3")},i=!e&&b,g=0,h,l,o,k,p;for(d.length&&(d+="/"),i&&(e=1);g<e;g++)for(h=0,i?(l=b,r.push(f(a))):(l=c[g].match(/@media ([^\{]+)\{([\S\s]+?)$/)&&RegExp.$1,r.push(RegExp.$2&&
f(RegExp.$2))),k=l.split(","),p=k.length;h<p;h++)o=k[h],j.push({media:o.match(/(only\s+)?([a-zA-Z]+)(\sand)?/)&&RegExp.$2,rules:r.length-1,minw:o.match(/\(min\-width:[\s]*([\s]*[0-9]+)px[\s]*\)/)&&parseFloat(RegExp.$1),maxw:o.match(/\(max\-width:[\s]*([\s]*[0-9]+)px[\s]*\)/)&&parseFloat(RegExp.$1)});w()},v,y,w=function(a){var d=z.clientWidth,b=e.compatMode==="CSS1Compat"&&d||e.body.clientWidth||d,d={},c=e.createDocumentFragment(),f=t[t.length-1],g=(new Date).getTime();if(a&&v&&g-v<30)clearTimeout(y),
y=setTimeout(w,30);else{v=g;for(var h in j)if(a=j[h],!a.minw&&!a.maxw||(!a.minw||a.minw&&b>=a.minw)&&(!a.maxw||a.maxw&&b<=a.maxw))d[a.media]||(d[a.media]=[]),d[a.media].push(r[a.rules]);for(h in i)i[h]&&i[h].parentNode===u&&u.removeChild(i[h]);for(h in d)a=e.createElement("style"),b=d[h].join("\n"),a.type="text/css",a.media=h,a.styleSheet?a.styleSheet.cssText=b:a.appendChild(e.createTextNode(b)),c.appendChild(a),i.push(a);u.insertBefore(c,f.nextSibling)}},b=function(a,b){var e=c();if(e)e.open("GET",
a,!0),e.onreadystatechange=function(){e.readyState==4&&(e.status==200||e.status==304)&&b(e.responseText)},e.readyState!=4&&e.send()},c=function(){for(var a=!1,b=[function(){return new ActiveXObject("Microsoft.XMLHTTP")},function(){return new XMLHttpRequest}],c=b.length;c--;){try{a=b[c]()}catch(e){continue}break}return function(){return a}}();s();respond.update=s;g.addEventListener?g.addEventListener("resize",q,!1):g.attachEvent&&g.attachEvent("onresize",q)}})(this,Modernizr.mq("only all"));
(function(g,f,q){function e(){for(var a=1,b=-1;l.length-++b;)if(l[b].s&&!(a=l[b].r))break;a&&r()}function z(a){var b=f.createElement("script"),d;b.src=a.s;b.onreadystatechange=b.onload=function(){!d&&(!b.readyState||b.readyState=="loaded"||b.readyState=="complete")&&(d=1,e(),b.onload=b.onreadystatechange=null)};h(function(){d||(d=1,e())},o.errorTimeout);a.e?b.onload():s.parentNode.insertBefore(b,s)}function j(b){var d=f.createElement("link"),c;d.href=b.s;d.rel="stylesheet";d.type="text/css";if(!b.e&&
(a||y)){var g=function(a){h(function(){if(!c)try{a.sheet.cssRules.length?(c=1,e()):g(a)}catch(b){b.code==1E3||b.message=="security"||b.message=="denied"?(c=1,h(function(){e()},0)):g(a)}},0)};g(d)}else d.onload=function(){c||(c=1,h(function(){e()},0))},b.e&&d.onload();h(function(){c||(c=1,e())},o.errorTimeout);!b.e&&s.parentNode.insertBefore(d,s)}function r(){var a=l.shift();v=1;a?a.t?h(function(){a.t=="c"?j(a):z(a)},0):(a(),e()):v=0}function i(a,d,c,g,i,j){function n(){!F&&(!m.readyState||m.readyState==
"loaded"||m.readyState=="complete")&&(C.r=F=1,!v&&e(),m.onload=m.onreadystatechange=null,h(function(){b.removeChild(m)},0))}var m=f.createElement(a),F=0,C={t:c,s:d,e:j};m.src=m.data=d;!w&&(m.style.display="none");m.width=m.height="0";a!="object"&&(m.type=c);m.onload=m.onreadystatechange=n;a=="img"?m.onerror=n:a=="script"&&(m.onerror=function(){C.e=C.r=1;r()});l.splice(g,0,C);b.insertBefore(m,w?null:s);h(function(){F||(b.removeChild(m),C.r=C.e=F=1,e())},o.errorTimeout)}function x(a,b,d){var c=b=="c"?
D:n;v=0;b=b||"j";E(a)?i(c,a,b,this.i++,t,d):(l.splice(this.i++,0,a),l.length==1&&r());return this}function u(){var a=o;a.loader={load:x,i:0};return a}var t=f.documentElement,h=g.setTimeout,s=f.getElementsByTagName("script")[0],A={}.toString,l=[],v=0,y="MozAppearance"in t.style,w=y&&!!f.createRange().compareNode,b=w?t:s.parentNode,c=g.opera&&A.call(g.opera)=="[object Opera]",a="webkitAppearance"in t.style,d=a&&"async"in f.createElement("script"),n=y?"object":c||d?"img":"script",D=a?"img":n,I=Array.isArray||
function(a){return A.call(a)=="[object Array]"},E=function(a){return typeof a=="string"},G=function(a){return A.call(a)=="[object Function]"},H=[],J={},K,o;o=function(a){function b(a){var a=a.split("!"),d=H.length,c=a.pop(),e=a.length,c={url:c,origUrl:c,prefixes:a},f,g;for(g=0;g<e;g++)f=J[a[g]],f&&(c=f(c));for(g=0;g<d;g++)c=H[g](c);return c}function d(a,c,e,f,g){var h=b(a),i=h.autoCallback;if(!h.bypass){c&&(c=G(c)?c:c[a]||c[f]||c[a.split("/").pop().split("?")[0]]);if(h.instead)return h.instead(a,
c,e,f,g);e.load(h.url,h.forceCSS||!h.forceJS&&/css$/.test(h.url)?"c":q,h.noexec);(G(c)||G(i))&&e.load(function(){u();c&&c(h.origUrl,g,f);i&&i(h.origUrl,g,f)})}}function c(a,b){function e(a){if(E(a))d(a,h,b,0,f);else if(Object(a)===a)for(i in a)a.hasOwnProperty(i)&&d(a[i],h,b,i,f)}var f=!!a.test,g=a.load||a.both,h=a.callback,i;e(f?a.yep:a.nope);e(g);a.complete&&b.load(a.complete)}var e,f,g=this.yepnope.loader;if(E(a))d(a,0,g,0);else if(I(a))for(e=0;e<a.length;e++)f=a[e],E(f)?d(f,0,g,0):I(f)?o(f):Object(f)===
f&&c(f,g);else Object(a)===a&&c(a,g)};o.addPrefix=function(a,b){J[a]=b};o.addFilter=function(a){H.push(a)};o.errorTimeout=1E4;f.readyState==null&&f.addEventListener&&(f.readyState="loading",f.addEventListener("DOMContentLoaded",K=function(){f.removeEventListener("DOMContentLoaded",K,0);f.readyState="complete"},0));g.yepnope=u()})(this,this.document);Modernizr.load=function(){yepnope.apply(window,[].slice.call(arguments,0))};
